logging:
  file: ./log/mvgapp.server.log
  level.: WARN

banner:
  location: banner/banner.txt

server:
  context-imagePath: /

spring:
  application:
    name: MVG App Server
    version: @project.version@
  jpa:
    hibernate:
      ddl-auto: validate
      use-new-id-generator-mappings: true
  profiles:
    active: development

security:
  basic:
    enabled: false

management:
  info:
    git:
      mode: full
